# Generated by Django 5.0.2 on 2024-02-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_class",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
