# Generated by Django 5.0.1 on 2024-02-15 18:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_inspectionresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspections",
                to="core.image",
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="inspection_errors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=120), size=10
            ),
        ),
        migrations.AlterModelTable(
            name="inspection",
            table="inspection",
        ),
    ]
